apiVersion: skaffold/v2beta10
kind: Config
build:
  artifacts:
    - image: keptn/helm-service
      docker:    # 	beta describes an artifact built from a Dockerfile.
        dockerfile: Dockerfile
        buildArgs:
          debugBuild: true

deploy:
  helm:
    releases:
      - name: keptn-helm-service
        artifactOverrides:
          image: keptn/helm-service
        chartPath: chart